# Generated by Django 4.2.6 on 2024-03-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('Cname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Ccode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccapital', models.IntegerField()),
                ('cname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.country')),
            ],
        ),
    ]
