# Generated by Django 4.2.6 on 2024-03-01 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topics',
            fields=[
                ('topics_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.topics')),
            ],
        ),
    ]
